name: example
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  secure_dotenv:
    path: ../secure_dotenv

dev_dependencies:
  build_runner: ^2.4.5
  secure_dotenv_generator:
    path: ../secure_dotenv_generator
  flutter_lints: ^2.0.1
  test: ^1.24.3

flutter:
